[default]
VERSION = '1.0.0'
LOG_FILENAME = 'log.log'
LOG_DATE_FORMAT = '%d/%m/%Y %H:%M:%S'
LOG_FORMAT = '%(asctime)s - %(name)s - %(levelname)s: %(filename)s : Def %(funcName)s : Line %(lineno)d : %(message)s'
LOG_MAX_BYTES = 60200
LOG_BACKUP_COUNT = 5
t=0

[development]
RESOURCES = 'resources/'
RESOURCES_DOWNLOADED = 'resources/downloaded/'
RESOURCES_DOWNLOADED_TIME_HISTORY = 'resources/downloaded/time_history/'
LOG_DIRECTORY = 'logs/'
PORT_FLASK = 8000
t=1

[production]
RESOURCES = 'resources/'
RESOURCES_DOWNLOADED = 'resources/downloaded/'
RESOURCES_DOWNLOADED_TIME_HISTORY = 'resources/downloaded/time_history/'
LOG_DIRECTORY = 'logs/'
PORT_FLASK = 8000
t=2