[default]
VERSION = '1.1.3'
LOG_FILENAME = 'log.log'
LOG_DATE_FORMAT = '%d/%m/%Y %H:%M:%S'
LOG_FORMAT = '%(asctime)s - %(name)s - %(levelname)s: %(filename)s : Def %(funcName)s : Line %(lineno)d : %(message)s'
LOG_MAX_BYTES = 50000
LOG_BACKUP_COUNT = 5
TIME_SEND_INFO = 18000


[development]
RESOURCES = 'resources/'
RESOURCES_DOWNLOADED = 'resources/downloaded/'
LOG_DIRECTORY = 'logs/'
PORT_FLASK = 8000


[production]
RESOURCES = 'resources/'
RESOURCES_DOWNLOADED = 'resources/downloaded/'
LOG_DIRECTORY = 'logs/'
PORT_FLASK = 8000
